default:
    stow --no-folding desktop
    stow bat
    stow ghostty
    stow git
    stow gtklock
    stow imv
    stow kanshi
    stow mako
    stow nvim
    stow oh-my-posh
    stow pacman
    stow paru
    stow ripgrep
    stow scripts
    stow spotify
    stow swappy
    stow sway
    stow taskwarrior
    stow taplo
    stow tidy-viewer
    stow tmux
    stow tofi
    stow uv
    stow waybar
    stow wezterm
    stow yazi
    stow zathura
    stow zsh
