#!/usr/bin/env bash

set -uxo pipefail

pacman_install() {
    sudo pacman -S --needed --noconfirm "$@"
}

paru_install() {
    paru -S --needed --noconfirm "$@"
}

# NOTE: run as newly created user

BUILD_REPOS="$HOME/build-repos"
PARU_REPO="$BUILD_REPOS/paru"

read -r -p "Confirm ready to setup system for user $USER with home $HOME (y/n): " confirm && [[ $confirm = [yY] ]] || exit 1

cd "$HOME" || exit 1

echo "Checking internet connection..."
ping -c 3 archlinux.org || { echo "Not connected to internet" && exit 1; }

# echo "Installing zsh packages and setting zsh as login shell..."
# zsh_pkgs=(
#     zsh
#     zsh-autosuggestions
#     zsh-completions
#     zsh-syntax-highlighting
# )
# pacman_install "${zsh_pkgs[@]}"
# chsh -s /usr/bin/zsh "$USER"

echo "Configuring /etc/pacman.conf..."
sudo sed -i "/Color/s/^#//g" /etc/pacman.conf
sudo sed -i "/VerbosePkgLists/s/^#//g" /etc/pacman.conf

echo "Updating before proceeding..."
sudo pacman -Syu --noconfirm
echo

echo "Installing and configuring reflector. Activating reflector.timer..."
pacman_install reflector
sudo tee /etc/xdg/reflector/reflector.conf > /dev/null <<"EOF"
--protocol https
--country US,CA
--latest 10
--sort rate
--save /etc/pacman.d/mirrorlist
EOF
sudo systemctl enable --now reflector.timer
echo

echo "Installing pacman-contrib and activating paccache.timer..."
pacman_install pacman-contrib
sudo systemctl enable --now paccache.timer
echo

echo "Setting up xdg-user-dirs and installing xdg-utils..."
pacman_install xdg-user-dirs xdg-utils
xdg-user-dirs-update
echo

echo "Installing paru..."
if ! type paru > /dev/null; then
    pacman_install rustup
    rustup default stable
    mkdir "$HOME/Documents/build-repos"
    git clone https://aur.archlinux.org/paru.git "$PARU_REPO"
    cd "$PARU_REPO" || exit 1
    makepkg -sirc --noconfirm
    cd "$HOME" || exit 1
else
    echo "paru already installed..."
fi
echo

echo "Installing Intel graphics packages..."
intel_graphics_pkgs=(
    mesa
    mesa-utils
    intel-media-driver
    libva-utils
)
paru_install "${intel_graphics_pkgs[@]}"
echo

echo "Installing Pipewire and other sound packages..."
sound_pkgs=(
    pipewire
    pipewire-audio
    pipewire-alsa
    pipewire-pulse
    pipewire-jack
    wireplumber
    pavucontrol
)
# NOTE: will be prompted to replace jack2 with pipewire-jack, so respond with "y" since
# default is "N"
# NOTE: can't use --no-confirm for this
printf "%s\n" y Y | paru -S --needed "${sound_pkgs[@]}"
echo

echo "Using rfkill to disable bluetooth..."
rfkill block bluetooth
echo

echo "Installing system maintenance packages..."
sys_maint_pkgs=(
    libsmbios
    nvme-cli
    smartmontools
    thermald
    trash-cli
    util-linux
)
paru_install "${sys_maint_pkgs[@]}"
echo "Enabling and starting thermald.service..."
sudo systemctl enable --now thermald.service
echo

echo "Enabling and starting fstrim.timer..."
sudo systemctl enable --now fstrim.timer
echo

# echo "Installing networking packages..."
# network_pkgs=(
#     networkmanager
#     network-manager-applet
# )
# paru_install "${network_pkgs[@]}"

echo "Mapping caps lock to escape and control..."
paru_install keyd
sudo tee /etc/keyd/default.conf > /dev/null <<"EOF"
[ids]

*

[main]

capslock = overload(control, esc)
EOF
sudo systemctl enable --now keyd.service

echo "Installing Sway and other core packages..."
sway_pkgs=(
    sway
    swayidle
    swaybg
    brightnessctl
    grim
    gtklock
    kanshi
    mako
    slurp
    solaar
    swappy
    waybar
    wl-clipboard
)
paru_install "${sway_pkgs[@]}"

echo "Installing fonts..."
font_pkgs=(
    ttf-zed-mono-nerd
    ttf-iosevka-nerd
    noto-fonts
    noto-fonts-cjk
    noto-fonts-emoji
)
paru_install "${font_pkgs[@]}"

echo "Installing Ghostty..."
paru_install ghostty

echo "Installing core tools..."
tools=(
    bat
    bottom
    dust
    dysk
    eza
    fd
    fzf
    jaq
    just
    ripgrep
    stow
    task
    tmux
    unzip
    usbutils
    wget
    xan
    yazi
    yt-dlp
    zip
    zoxide
)
paru_install "${tools[@]}"

echo "Installing Lua packages..."
lua_dev_pkgs=(
    lua-language-server
    selene
    stylua
)
paru_install "${lua_dev_pkgs[@]}"
echo

echo "Installing Python packages..."
python_dev_pkgs=(
    ruff
    uv
)
paru_install "${python_dev_pkgs[@]}"
# NOTE: use of system python? Do tool install AFTER uv config stowed?
# uv tool install basedpyright
echo

echo "Installing Go packages..."
go_dev_pkgs=(
    go
    go-tools
    gopls
)
paru_install "${go_dev_pkgs[@]}"
echo

echo "Installing Typst packages..."
typst_dev_pkgs=(
    typst
    tinymist
)
paru_install "${typst_dev_pkgs[@]}"
echo

echo "Installing JS/TS packages..."
js_dev_pkgs=(
    pnpm
    typescript-language-server
    vscode-html-languageserver
    vscode-css-languageserver
    vscode-json-languageserver
)
paru_install  "${js_dev_pkgs[@]}"
# echo "Installing Astro LSP as global package via pnpm..."
# NOTE: pnpm setup creates .zshrc if needed and writes some code for setting folder; would rather set myself
# pnpm setup
# pnpm install -g @astrojs/language-server
echo

echo "Installing Rust packages..."
rust_dev_pkgs=(
    rust-analyzer
)
paru_install "${rust_dev_pkgs[@]}"
echo

echo "Installing other dev packages..."
dev_pkgs=(
    bash-language-server
    markdownlint-cli2
    marksman
    shellcheck
    taplo-cli
    yaml-language-server
)
paru_install "${dev_pkgs[@]}"
echo

echo "Building and installing Neovim from source..."
nvim_pkgs=(
    base-devel
    cmake
    curl
    ninja
    tree-sitter-cli
    unzip
)
paru_install "${nvim_pkgs[@]}"
git clone https://github.com/neovim/neovim.git "$BUILD_REPOS/neovim"
cd "$BUILD_REPOS/neovim" || exit 1
git remote set-url origin git@github.com:neovim/neovim.git
git remote set-url --push origin git@github.com:neovim/neovim.git
git checkout nightly
make CMAKE_BUILD_TYPE=RelWithDebInfo
sudo make install
cd "$HOME" || exit 1

echo "Installing theming packages. Must still set theme manually..."
theming_pkgs=(
    kvantum
    kvantum-qt5
    kvantum-theme-materia
    materia-gtk-theme
    nwg-look
)
paru_install "${theming_pkgs[@]}"
echo

echo "Installing XDG desktop portals..."
xdg_portal_pkgs=(
    xdg-desktop-portal
    xdg-desktop-portal-wlr
    xdg-desktop-portal-gtk
)
paru_install "${xdg_portal_pkgs[@]}"
echo

echo "Installing Nemo and setting as default file manager..."
paru_install nemo
# set as default file browser
xdg-mime default nemo.desktop inode/directory application/x-gnome-saved-search
# set Wezterm as default terminal for Nemo
gsettings set org.cinnamon.desktop.default-applications.terminal exec wezterm

echo "Installing other apps..."
app_pkgs=(
    amberol
    chromaprint
    gst-libav
    imv
    mpv
    picard
    qt5-wayland
    spotify-launcher
)
paru_install "${app_pkgs[@]}"

zathura_pkgs=(
    zathura
    zathura-pdf-mupdf
)
paru -S --needed "${zathura_pkgs[@]}"
# printf "%s\n" 30 Y | paru -S --needed "${zathura_pkgs[@]}"

echo "Installing AUR packages..."
aur_pkgs=(
    oh-my-posh-bin
    slack-desktop
    tofi
    wezterm-git
)
# NOTE: will require manual responses
paru -S --needed "${aur_pkgs[@]}"


# echo "Installing flow..."
# go install github.com/winter-again/flow@latest

echo "Cloning dotfiles, setting SSH URL, and stowing dotfiles..."
git clone https://github.com/winter-again/.dotfiles.git
cd "$HOME/.dotfiles" || exit 1
git remote set-url origin git@github.com:winter-again/.dotfiles.git
git remote set-url --push origin git@github.com:winter-again/.dotfiles.git
just
cd "$HOME" || exit 1

# echo "Installing ufw and activating firewall..."
# paru_install ufw
# sudo systemctl enable --now ufw.service
# sudo ufw enable

# TODO: consider removing the below

# echo "Installing rclone, restic, and rsync for backups..."
# paru_install rclone restic rsync
# git clone https://github.com/winter-again/backups.git "$HOME/Documents/code/backups"
# cd "$HOME/Documents/code/backups" || exit 1
# git remote set-url origin git@github.com:winter-again/backups.git
# git remote set-url --push origin git@github.com:winter-again/backups.git
# just lab
# just personal
# cd "$HOME" || exit 1

echo
echo "Done. Reboot the system..."
