#!/usr/bin/env bash

set -uo pipefail

pacman_install() {
    sudo pacman -S --needed --noconfirm "$1"
}

paru_install() {
    sudo paru -S --needed --noconfirm "$1"
}

# NOTE: run as newly created user

BUILD_REPOS="$HOME/build-repos"
PARU_REPO="$BUILD_REPOS/paru"

read -r -p "Confirm ready to setup system for user $USER with home $HOME (y/n): " confirm && [[ $confirm = [yY] ]] || exit 1

cd "$HOME" || exit 1

echo "Checking internet connection..."
ping -c 3 archlinux.org || { echo "Not connected to internet" && exit 1; }
clear

echo "Installing zsh packages and setting zsh as login shell..."
zsh_pkgs=(
    zsh
    zsh-autosuggestions
    zsh-completions
    zsh-syntax-highlighting
)
pacman_install "${zsh_pkgs[@]}"
chsh -s /usr/bin/zsh "$USER"

echo "Configuring /etc/pacman.conf..."
sudo sed -i "/Color/s/^#//g" /etc/pacman.conf
sudo sed -i "/VerbosePkgLists/s/^#//g" /etc/pacman.conf

echo "Updating before proceeding..."
sudo pacman -Syu --noconfirm
clear

echo "Installing and configuring reflector. Activating reflector.timer..."
pacman_install reflector
sudo tee /etc/xdg/reflector/reflector.conf > /dev/null <<"EOF"
--protocol https
--country US,CA
--latest 10
--sort rate
--save /etc/pacman.d/mirrorlist
EOF
sudo systemctl enable --now reflector.timer

echo "Installing pacman-contrib and activating paccache.timer..."
pacman_install pacman-contrib
sudo systemctl enable --now paccache.timer

echo "Setting up xdg-user-dirs and installing xdg-utils..."
pacman_install xdg-user-dirs xdg-utils
xdg-user-dirs-update

echo "Installing paru..."
pacman_install rustup
rustup default stable
mkdir "$HOME/Documents/build-repos"
git clone https://aur.archlinux.org/paru.git "$PARU_REPO"
cd "$PARU_REPO" || exit 1
makepkg -sirc --noconfirm
cd "$HOME" || exit 1

echo "Installing Intel graphics packages..."
intel_graphics_pkgs=(
    mesa
    mesa-utils
    intel-media-driver
    libva-utils
)
paru_install "${intel_graphics_pkgs[@]}"

echo "Installing Pipewire and other sound packages..."
sound_pkgs=(
    pipewire
    pipewire-audio
    pipewire-alsa
    pipewire-pulse
    pipewire-jack
    wireplumber
    pavucontrol
)
# NOTE: will be prompted to replace jack2 with pipewire-jack, so respond with "y" since
# default is "N"
echo "y" | paru_install "${sound_pkgs[@]}"

echo "Using rfkill to disable bluetooth..."
rfkill block bluetooth

echo "Installing system maintenance packages..."
sys_maint_pkgs=(
    libsmbios
    nvme-cli
    smartmontools
    thermald
    trash-cli
    util-linux
)
paru_install "${sys_maint_pkgs[@]}"
echo "Enabling and starting thermald.service..."
sudo systemctl enable --now thermald.service
echo "Enabling and starting fstrim.timer..."
sudo systemctl enable --now fstrim.timer

echo "Installing networking packages..."
network_pkgs=(
    networkmanager
    network-manager-applet
)
paru_install "${network_pkgs[@]}"

echo "Mapping caps lock to escape and control..."
paru_install keyd
sudo tee /etc/keyd/default.conf > /dev/null <<"EOF"
[ids]

*

[main]

capslock = overload(control, esc)
EOF

echo "Installing Sway and other core packages..."
sway_pkgs=(
    sway
    swayidle
    swaybg
    brightnessctl
    grim
    gtklock
    kanshi
    mako
    slurp
    solaar
    swappy
    tofi
    waybar
    wl-clipboard
)
paru_install "${sway_pkgs[@]}"

echo "Installing fonts..."
font_pkgs=(
    ttf-zed-mono-nerd
    ttf-iosevka-nerd
    noto-fonts
    noto-fonts-cjk
    noto-fonts-emoji
)
paru_install "${font_pkgs[@]}"

echo "Installing Wezterm and Ghostty..."
terminals=(
    wezterm-git
    ghostty
)
paru_install "${terminals[@]}"

echo "Installing core tools..."
tools=(
    bat
    bc
    bottom
    dust
    dysk
    eza
    fd
    fzf
    jaq
    just
    oh-my-posh-bin
    ripgrep
    stow
    task
    tmux
    usbutils
    wget
    xan
    yazi
    yt-dlp
    zip
    zoxide
)
paru_install "${tools[@]}"

echo "Installing Lua packages..."
lua_dev_pkgs=(
    lua-language-server
    selene
    stylua
)
paru_install "${lua_dev_pkgs[@]}"

echo "Installing Python packages..."
python_dev_pkgs=(
    ruff
    uv
)
paru_install "${python_dev_pkgs[@]}"
uv tool install basedpyright

echo "Installing Go packages..."
go_dev_pkgs=(
    go
    go-tools
    gopls
)
paru_install "${go_dev_pkgs[@]}"

echo "Installing Typst packages..."
typst_dev_pkgs=(
    typst
    tinymist
)
paru_install "${typst_dev_pkgs[@]}"

echo "Installing JS/TS packages..."
js_dev_pkgs=(
    pnpm
    typescript-language-server
    vscode-html-languageserver
    vscode-css-languageserver
    vscode-json-languageserver
)
paru_install  "${js_dev_pkgs[@]}"
echo "Installing Astro LSP as global package via pnpm..."
pnpm install -g @astrojs/language-server

echo "Installing Rust packages..."
rust_dev_pkgs=(
    rust-analyzer
)
paru_install "${rust_dev_pkgs[@]}"

echo "Installing other dev packages..."
dev_pkgs=(
    bash-language-server
    markdownlint-cli2
    marksman
    shellcheck
    taplo-cli
    yaml-language-server
)
paru_install "${dev_pkgs[@]}"

echo "Building and installing Neovim from source..."
nvim_pkgs=(
    base-devel
    cmake
    curl
    ninja
    tree-sitter-cli
    unzip
)
paru_install "${nvim_pkgs[@]}"
git clone https://github.com/neovim/neovim.git "$BUILD_REPOS/neovim"
cd "$BUILD_REPOS/neovim" || exit 1
git remote set-url origin git@github.com:neovim/neovim.git
git remote set-url --push origin git@github.com:neovim/neovim.git
git checkout nightly
make CMAKE_BUILD_TYPE=RelWithDebInfo
sudo make install
cd "$HOME" || exit 1

# echo "Installing theming packages. Must still set theme manually..."
# theming_pkgs=(
#     kvantum
#     kvantum-qt5
#     kvantum-theme-materia
#     materia-gtk-theme
#     nwg-look
# )
# paru_install "${theming_pkgs[@]}"

echo "Installing XDG desktop portals..."
xdg_portal_pkgs=(
    xdg-desktop-portal
    xdg-desktop-portal-wlr
    xdg-desktop-portal-gtk
)
paru_install "${xdg_portal_pkgs[@]}"

echo "Installing Nemo and setting as default file manager..."
paru_install nemo
# set as default file browser
xdg-mime default nemo.desktop inode/directory application/x-gnome-saved-search
# set Wezterm as default terminal for Nemo
gsettings set org.cinnamon.desktop.default-applications.terminal exec wezterm

echo "Installing other apps..."
app_pkgs=(
    amberol
    chromaprint
    gst-libav
    imv
    mpv
    picard
    qt5-wayland
    slack-desktop
    spotify-launcher
    zathura
    zathura-pdf-mupdf
)
paru_install "${app_pkgs[@]}"
echo 30 | paru_install "${sound_pkgs[@]}"

echo "Installing flow..."
go install github.com/winter-again/flow@latest

echo "Setting SSH URL for dotfiles repo and stowing dotfiles..."
cd "$HOME/.dotfiles" || exit 1
git remote set-url origin git@github.com:winter-again/.dotfiles.git
git remote set-url --push origin git@github.com:winter-again/.dotfiles.git
just stow
cd "$HOME" || exit 1

# echo "Installing ufw and activating firewall..."
# paru_install ufw
# sudo systemctl enable --now ufw.service
# sudo ufw enable

# TODO: consider removing the below

# echo "Installing rclone, restic, and rsync for backups..."
# paru_install rclone restic rsync
# git clone https://github.com/winter-again/backups.git "$HOME/Documents/code/backups"
# cd "$HOME/Documents/code/backups" || exit 1
# git remote set-url origin git@github.com:winter-again/backups.git
# git remote set-url --push origin git@github.com:winter-again/backups.git
# just lab
# just personal
# cd "$HOME" || exit 1

echo
echo "Done. Reboot the system..."
