# MARKDOWN SETTINGS
[format.markdown]

# Format used to generate links between notes.
# Either "wiki", "markdown" or a custom template. Default is "markdown".
# NOTE: using custom format breaks some things like ZkLinks/ZkBacklinks commands
link-format = "[{{ title }}]({{ path }})"
# Indicates whether a link's path will be percent-encoded.
# Defaults to true for "markdown" format and false for "wiki" format.
link-encode-path = false
# Indicates whether a link's path file extension will be removed.
# Defaults to true.
link-drop-extension = false

# Enable support for #hashtags.
hashtags = true
# Enable support for :colon:separated:tags:.
colon-tags = false
# Enable support for Bear's #multi-word tags#
# Hashtags must be enabled for multi-word tags to work.
multiword-tags = false
