# inspired from: https://github.com/andrew8088/dotfiles/blob/main/starship/starship.toml
# with tokyonight colors from folke
format = """
[╭─](#c0caf5)[](#7aa2f7)\
$os\
$username\
$hostname\
$directory\
[ ](#7aa2f7)\
$git_branch\
$git_state\
$git_status\
$fill\
$python $rlang $nodejs $jobs $cmd_duration [](#292e42)$time[ ](#292e42)\
$line_break\
[╰─ ](#c0caf5)$character"""

command_timeout = 1000
add_newline = true

[os]
disabled = true

[os.symbols]
Pop = ''

[username]
style_user = 'white bold'
style_root = 'black bold'
format = '[$user]($style) '
show_always = false

[hostname]
ssh_only = true
ssh_symbol = 'ssh'

[directory]
read_only = '󰌾'
truncation_length = 4
truncate_to_repo = false
truncation_symbol = '…/' 
format = '[$path ]($style)[$read_only]($read_only_style)'
style = 'fg:#1a1b26 bg:#7aa2f7'
read_only_style = 'fg:#db4b4b bg:#7aa2f7'
home_symbol = ' ~'

[git_state]
format = '[\($state( $progress_current/$progress_total)\)]($style) '
style = '#f1502f'

[git_branch]
symbol = ''
format = '[$symbol $branch(:$remote_branch)]($style)'
style = 'bold #f1502f'

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
style = 'bold #f1502f'
conflicted = '󰃸${count}'
ahead = '⇡${count}'
behind = '⇣${count}'
diverged = '󰃻 ⇡${ahead_count}⇣${behind_count}'
untracked = '?${count}'
stashed = ''
modified = '!${count}'
staged = '+${count}'
renamed = '»${count}'
deleted = '✘${count}'

[fill]
symbol = ' '

[python]
pyenv_version_name = true
pyenv_prefix = 'pyenv'
symbol = ''
format = '[${symbol} ${pyenv_prefix} \[(${version})\](\($virtualenv\))]($style)'

[rlang]
format = '[$symbol ($version)]($style)'
symbol = ''

[nodejs]
format = '[$symbol\[($version\] )]($style)'

[jobs]
symbol = ''
format = '[$symbol]($style)'

[cmd_duration]
format = '[$duration]($style)'
style = '#9d7cd8'

[time]
disabled = false
time_format = "%I:%M %p"
format = '[[  $time ](fg:#c0caf5 bg:#292e42)]($style)'

[character]
disabled = true
