[colors]
foreground = "#f0f0f0"
background = "#0f0f0f"
cursor_bg = "#f0f0f0"
# removing this prevents covering char under cursor with the fg color
# cursor_fg = "#f0f0f0"
cursor_border = "#f0f0f0"
split = "#4c4c4c"
ansi = [
    "#0f0f0f",
    "#b36d7c",
    "#778c73",
    "#aca98a",
    "#8f8aac",
    "#ac8aac",
    "#8aabac",
    "#f0f0f0",
]
brights = [
    "#4c4c4c",
    "#c48282",
    "#8aac8b",
    "#c4c19e",
    "#a39ec4",
    "#c49ec4",
    "#9ec3c4",
    "#f0f0f0",
]
